query GetProducts($limit: Int = 8) {
  products(limit: $limit) {
    id
    title
    price
    category {
      name
      image
    }
    images
  }
}

query getProduct($id:ID!) {
  product(id:$id) {
    description
    title
    price
    images
    category {
      name
      image
    }
  }
}